In [1]:
import pandas as pd
import numpy as np
import statistics
from scipy import stats
pd.read_csv("C:\\Users\\bharvath\\Downloads\\la.csv")
dat=pd.read_csv("C:\\Users\\bharvath\\Downloads\\la.csv")
df=pd.DataFrame(dat)
df.info()
cols=[1,2,3,4,5,7,8,9,10,11,12,13]
df=df[df.columns[cols]]
df.head()
mv=df['Crime Code'].mean()
mv
del df['MO Codes']
df
df['Time Occurred']=df['Time Occurred'].fillna(df['Time Occurred'].mean())
df.info()
df['Victim Age']=df['Victim Age'].fillna(df['Victim Age'].mean())
df['Premise Code']=df['Premise Code'].fillna(df['Premise Code'].mean())
df.info()
df['Victim Sex']=df['Victim Sex'].fillna("Any Victim")
df.info()
df['Victim Descent']=df['Victim Descent'].fillna("Any Descent")
df.info()
df
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize 
   
ps = PorterStemmer()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 23 columns):
Date Reported                        499 non-null object
Date Occurred                        499 non-null object
Time Occurred                        499 non-null int64
Area ID                              499 non-null int64
Area Name                            499 non-null object
Reporting District                   499 non-null int64
Crime Code                           499 non-null int64
Crime Code Description               499 non-null object
MO Codes                             218 non-null object
Victim Age                           467 non-null float64
Victim Sex                           498 non-null object
Victim Descent                       498 non-null object
Premise Code                         499 non-null int64
Premise Description                  499 non-null object
Address                              499 non-null object
Cross Street                         457 non-null object
Location                             499 non-null object
Zip Codes                            499 non-null int64
Census Tracts                        494 non-null float64
Precinct Boundaries                  497 non-null float64
LA Specific Plans                    169 non-null float64
Council Districts                    497 non-null float64
Neighborhood Councils (Certified)    483 non-null float64
dtypes: float64(6), int64(6), object(11)
memory usage: 89.7+ KB

KeyError: 'Crime Code'

In [4]:
df.mean()

Time Occurred    1345.997691
Area ID            10.415704
Crime Code        997.000000
Victim Age         38.791155
Premise Code      101.249423
dtype: float64

In [5]:
df.median()

Time Occurred    1430.0
Area ID            11.0
Crime Code        997.0
Victim Age         38.0
Premise Code      101.0
dtype: float64

In [6]:
df.mode()

,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Crime Code,Crime Code Description,Victim Age,Victim Sex,Victim Descent,Premise Code
0,2019-06-12T00:00:00.000,2019-06-11T00:00:00.000,800,1,Central,997,TRAFFIC COLLISION,18.0,M,H,101

In [7]:
gmean=stats.gmean(df.Area ID)
print('gmean is',gmean)

SyntaxError: invalid syntax (<ipython-input-7-2e7b1402a4ff>, line 1)

In [8]:
from scipy import stats

In [9]:
gmean=stats.gmean(df.Area ID)
print('gmean is',gmean)

SyntaxError: invalid syntax (<ipython-input-9-2e7b1402a4ff>, line 1)

In [12]:
gmean=stats.gmean(df['Area ID'])
print('gmean is',gmean)

gmean is 7.841158208456369

In [10]:
hmean=stats.hmean(df['Area ID'])
print('hmean is',hmean)

hmean is 4.823285125142514

In [ ]:
df.describe()

In [ ]:
plt.hist(df.Area ID)

In [ ]:
plt.hist(df.Area ID)

In [ ]:
plt.hist(df['Area ID'])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(df['Area ID'])

In [ ]:
freq = {}

In [ ]:
for item in df.Victim Age: 
        if (item in freq): 
            freq[item] += 1
        else: 
            freq[item] = 1

In [ ]:
for item in df['Victim Age']: 
        if (item in freq): 
            freq[item] += 1
        else: 
            freq[item] = 1

In [ ]:
key=[x for x in freq.keys()]

In [ ]:
key

In [ ]:
value=[freq[x] for x in freq.keys()]
value

In [ ]:
plt.pie(value,labels=key,autopct='%.1f%%',startangle=90)
plt.show()

In [13]:
plt.bar(key,value)
plt.show()

NameError: name 'plt' is not defined

In [ ]:
df = pd.DataFrame(np.random.rand(10, 5), columns=['1', '2', '3', '4', '5'])
df.plot.box(grid='True')

In [ ]:
df = pd.DataFrame(np.random.rand(10, 5), columns=['1', '2', '3', '4', '5'])
df.plot.box(grid='False')

In [2]:
df

,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code Description,MO Codes,Victim Age,Victim Sex,Victim Descent,Premise Code,Premise Description
0,2019-08-03T00:00:00.000,1035,16,Foothill,1633,TRAFFIC COLLISION,NaN,38.0,F,H,101,STREET
1,2019-08-03T00:00:00.000,330,2,Rampart,245,TRAFFIC COLLISION,NaN,54.0,M,A,101,STREET
2,2019-08-03T00:00:00.000,1300,9,Van Nuys,919,TRAFFIC COLLISION,NaN,43.0,F,H,108,PARKING LOT
3,2019-08-03T00:00:00.000,1410,9,Van Nuys,935,TRAFFIC COLLISION,NaN,32.0,M,H,101,STREET
4,2019-08-03T00:00:00.000,945,10,West Valley,1065,TRAFFIC COLLISION,NaN,54.0,M,W,101,STREET
5,2019-08-03T00:00:00.000,1250,19,Mission,1993,TRAFFIC COLLISION,NaN,40.0,F,H,101,STREET
6,2019-08-03T00:00:00.000,1405,9,Van Nuys,941,TRAFFIC COLLISION,NaN,19.0,F,H,101,STREET
7,2019-08-03T00:00:00.000,140,15,N Hollywood,1503,TRAFFIC COLLISION,NaN,21.0,M,W,101,STREET
8,2019-08-03T00:00:00.000,1240,19,Mission,1995,TRAFFIC COLLISION,NaN,49.0,M,H,108,PARKING LOT
9,2019-08-03T00:00:00.000,1210,20,Olympic,2029,TRAFFIC COLLISION,NaN,22.0,F,H,101,STREET
10,2019-08-03T00:00:00.000,715,16,Foothill,1693,TRAFFIC COLLISION,NaN,51.0,M,O,101,STREET
11,2019-08-03T00:00:00.000,300,19,Mission,1924,TRAFFIC COLLISION,NaN,41.0,M,H,101,STREET
12,2019-08-03T00:00:00.000,1605,7,Wilshire,765,TRAFFIC COLLISION,NaN,33.0,M,W,101,STREET
13,2019-08-03T00:00:00.000,150,17,Devonshire,1716,TRAFFIC COLLISION,NaN,47.0,M,W,101,STREET
14,2019-08-02T00:00:00.000,1010,19,Mission,1956,TRAFFIC COLLISION,NaN,39.0,F,H,101,STREET
15,2019-08-02T00:00:00.000,2205,8,West LA,836,TRAFFIC COLLISION,605,NaN,X,X,101,STREET
16,2019-08-02T00:00:00.000,35,16,Foothill,1619,TRAFFIC COLLISION,3006 3037 3030 3028 3101 3401 3701 4026,NaN,M,O,101,STREET
17,2019-08-02T00:00:00.000,930,15,N Hollywood,1585,TRAFFIC COLLISION,605,18.0,M,X,108,PARKING LOT
18,2019-08-02T00:00:00.000,640,9,Van Nuys,994,TRAFFIC COLLISION,NaN,76.0,M,W,101,STREET
19,2019-08-02T00:00:00.000,735,20,Olympic,2021,TRAFFIC COLLISION,NaN,50.0,F,W,101,STREET
20,2019-08-02T00:00:00.000,155,19,Mission,1988,TRAFFIC COLLISION,NaN,18.0,M,O,101,STREET
21,2019-08-02T00:00:00.000,1200,10,West Valley,1035,TRAFFIC COLLISION,NaN,18.0,M,W,101,STREET
22,2019-08-02T00:00:00.000,2015,8,West LA,891,TRAFFIC COLLISION,NaN,34.0,M,W,101,STREET
23,2019-08-02T00:00:00.000,2100,5,Harbor,585,TRAFFIC COLLISION,605,18.0,X,X,101,STREET
24,2019-08-02T00:00:00.000,735,19,Mission,1993,TRAFFIC COLLISION,NaN,39.0,M,H,101,STREET
25,2019-08-02T00:00:00.000,1245,5,Harbor,514,TRAFFIC COLLISION,605,33.0,F,B,101,STREET
26,2019-08-02T00:00:00.000,900,17,Devonshire,1735,TRAFFIC COLLISION,NaN,77.0,M,W,101,STREET
27,2019-08-02T00:00:00.000,930,4,Hollenbeck,469,TRAFFIC COLLISION,NaN,53.0,M,H,101,STREET
28,2019-08-02T00:00:00.000,1715,16,Foothill,1663,TRAFFIC COLLISION,NaN,63.0,M,W,101,STREET
29,2019-08-02T00:00:00.000,1555,21,Topanga,2126,TRAFFIC COLLISION,NaN,46.0,M,O,101,STREET
...,...,...,...,...,...,...,...,...,...,...,...,...
469,2019-07-29T00:00:00.000,1635,5,Harbor,523,TRAFFIC COLLISION,605,60.0,F,H,101,STREET
470,2019-07-29T00:00:00.000,1315,7,Wilshire,776,TRAFFIC COLLISION,NaN,18.0,M,O,101,STREET
471,2019-07-29T00:00:00.000,1110,3,Southwest,358,TRAFFIC COLLISION,3036 3004 3028 3030 3101,26.0,M,B,101,STREET
472,2019-07-29T00:00:00.000,1310,19,Mission,1981,TRAFFIC COLLISION,NaN,39.0,M,W,101,STREET
473,2019-07-29T00:00:00.000,1340,14,Pacific,1469,TRAFFIC COLLISION,NaN,55.0,F,H,101,STREET
474,2019-07-29T00:00:00.000,1330,1,Central,138,TRAFFIC COLLISION,3101 3401 3701 3011 3032,NaN,M,W,108,PARKING LOT
475,2019-07-29T00:00:00.000,1450,19,Mission,1966,TRAFFIC COLLISION,NaN,22.0,M,H,101,STREET
476,2019-07-29T00:00:00.000,1715,17,Devonshire,1701,TRAFFIC COLLISION,3004 3029 3037 3025 3101 3401 3701 4026,28.0,M,A,101,STREET
477,2019-07-29T00:00:00.000,2200,15,N Hollywood,1516,TRAFFIC COLLISION,605,21.0,M,H,101,STREET
478,2019-07-29T00:00:00.000,1930,19,Mission,1934,TRAFFIC COLLISION,3011 3037 3034 3028 3032 3102 3401 3701 4026,NaN,M,W,108,PARKING LOT
479,2019-07-29T00:00:00.000,1814,18,Southeast,1837,TRAFFIC COLLISION,NaN,50.0,F,H,101,STREET
480,2019-07-29T00:00:00.000,1430,20,Olympic,2023,TRAFFIC COLLISION,605,30.0,M,K,101,STREET
481,2019-07-29T00:00:00.000,2100,13,Newton,1371,TRAFFIC COLLISION,3101 3401 3701 3003 3026 3029,18.0,M,H,101,STREET
482,2019-07-29T00:00:00.000,2000,5,Harbor,528,TRAFFIC COLLISION,605,18.0,X,X,101,STREET
483,2019-07-29T00:00:00.000,1430,8,West LA,835,TRAFFIC COLLISION,605,42.0,M,B,101,STREET
484,2019-07-29T00:00:00.000,730,9,Van Nuys,974,TRAFFIC COLLISION,NaN,30.0,M,O,101,STREET
485,2019-07-29T00:00:00.000,1055,18,Southeast,1822,TRAFFIC COLLISION,1501,32.0,F,H,101,STREET
486,2019-07-29T00:00:00.000,1820,19,Mission,1958,TRAFFIC COLLISION,NaN,54.0,F,H,101,STREET
487,2019-07-29T00:00:00.000,1951,12,77th Street,1233,TRAFFIC COLLISION,4025 3037 3006 3028 3039 3101,NaN,F,H,101,STREET
488,2019-07-29T00:00:00.000,1735,18,Southeast,1831,TRAFFIC COLLISION,1501,NaN,M,O,101,STREET
489,2019-07-29T00:00:00.000,1830,8,West LA,881,TRAFFIC COLLISION,605,18.0,X,X,101,STREET
490,2019-07-29T00:00:00.000,1730,9,Van Nuys,911,TRAFFIC COLLISION,NaN,28.0,F,O,101,STREET
491,2019-07-29T00:00:00.000,1100,13,Newton,1371,TRAFFIC COLLISION,4025 0101 3026 3029 3101 3036 3008,58.0,M,B,101,STREET
492,2019-07-29T00:00:00.000,624,12,77th Street,1263,TRAFFIC COLLISION,605,33.0,M,X,101,STREET
493,2019-07-29T00:00:00.000,1630,11,Northeast,1153,TRAFFIC COLLISION,3101 3401 3701 3004 3026,17.0,M,W,101,STREET
494,2019-07-29T00:00:00.000,30,10,West Valley,1011,TRAFFIC COLLISION,NaN,55.0,M,O,101,STREET
495,2019-07-29T00:00:00.000,1500,17,Devonshire,1791,TRAFFIC COLLISION,NaN,56.0,M,H,101,STREET
496,2019-07-29T00:00:00.000,520,14,Pacific,1469,TRAFFIC COLLISION,1501,57.0,M,B,101,STREET
497,2019-07-29T00:00:00.000,1230,3,Southwest,341,TRAFFIC COLLISION,NaN,55.0,F,O,101,STREET
498,2019-07-29T00:00:00.000,300,19,Mission,1902,TRAFFIC COLLISION,3011 3036 3030 3028 3101 3401 3701 4019,NaN,F,H,101,STREET

In [6]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
import numpy as np
import statistics
from scipy import stats
import csv
with open("C:\\Users\\bharvath\\Downloads\\la.csv", 'r') as f:
    wines = list(csv.reader(f, delimiter=";"))

import numpy as np
wines = np.array(wines, dtype=np.float)

NameError: name 'columns' is not defined

In [5]:
DF.INFO()

NameError: name 'DF' is not defined